### ISSUE TITLE
latest soapy commits for gr-osmosdr

### ISSUE THREAD

**Issue by starvald** [pothosware/SoapySDR#109]
Sorry if this isn't the place but i can't find an issues tab in gr-osmosdr.

re: 2 Commits on Feb 2, 2017
recompiled gr-osmosdr as i noticed the latest commits but it's only half working.

the waterfall is showing a signal but the panadapter is flatlined, tried my airspy and sdrplay pro2.
is this a soapysdr or gqrx problem?

![screenshot from 2017-02-05 17-17-51](https://cloud.githubusercontent.com/assets/20885830/22628176/4ca308a8-ebc7-11e6-8f43-bd2617911522.png)

**Comment by guruofquality** [comment]
So the only major change in gr-osmosdr is that devices supported through SoapySDR will show up in the device list in GQRX. Provided that soapysdr was installed, and modules for like airspy and sdrplay are available.

So I doubt that there is any reversion, but are you perhaps comparing SoapyAirspy (which is in the screenshot) to the behaviour of the [lib/airspy](https://github.com/osmocom/gr-osmosdr/tree/master/lib/airspy) support  in gr-osmosdr? If so, I want to make sure that nothing is broken in gr-osmosdr. Can you still select the original airspy and sdr play that are directly an option in gr-osmosdr compile options?

And if there is some difference for the controls, maybe we should fix SoapyAirspy or SoapySDRPlay to match. I don't know what control could break the panadapter, so I'm not sure how this could be affected by different hardware modules. @csete sorry to bother, but any idea about the screenshot above?

**Comment by csete** [comment]
I think it's a gqrx problem that can happen regardless of the driver backend. Try resetting the configuration using "gqrx -r" (nb: you will loose settings but I have no other solution at the moment)

**Comment by starvald** [comment]
Sorted, i needed to reset the gqrx config as you suggested.

**Comment by guruofquality** [comment]
ok looks like everything is ok. thanks!
