### ISSUE TITLE
Compiling installs the lib in a strange path

### ISSUE THREAD

**Issue by bogdanr** [pothosware/SoapySDR#114]
I am compiling it like this:
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_INSTALL_DIR:PATH=lib64 ..`

but when I run `make install`, the libs, such as (libSoapySDR.so.0.6-dev) end up in `/urs/lib` instead of `/usr/lib64`

Moving the libs manually to `/usr/lib64` makes thing work.

**Comment by guruofquality** [comment]
Use `-DLIB_SUFFIX=64` (see https://github.com/pothosware/SoapySDR/blob/master/lib/CMakeLists.txt#L80)

We try to guess this, but its not perfect: https://github.com/pothosware/SoapySDR/blob/master/cmake/SoapySDRConfig.cmake#L26

Just curious, but what OS/linux flavour are you installing on?

**Comment by bogdanr** [comment]
I am installing on [NimbleX](http://nimblex.net/) which is somewhat close to Slackware-current as the build environment is concerned.
