### ISSUE TITLE
cannot define dllimport entity in ConverterRegistery.cpp

### ISSUE THREAD

**Issue by ALHasani** [pothosware/SoapySDR#153]
In an attempt to build the SoapySDR in Visual Studio, I receive the error E1391 described as "cannot define dllimport entity" and related to line 8 of "ConverterRegistery.cpp".

**Comment by guruofquality** [comment]
A minor issue from the recent merge, it does work in vc 12 fwiw: https://ci.appveyor.com/project/guruofquality/soapysdr/build/297/job/y3h6iu4w9moacas7 In the meantime, use the maint branch or release tag. Will fix shortly.
