### ISSUE TITLE
Unchecked C-style memory allocations in SoapySDRKwargs_set

### ISSUE THREAD

**Issue by BatchDrake** [pothosware/SoapySDR#173]
https://github.com/pothosware/SoapySDR/blob/937131be31c1fad2859ddb9eb3ad90d813280b0a/lib/TypesC.cpp#L44

This function performs several C-style memory allocations (`realloc`, `strdup`) that may return `NULL` on failure, but none of them are checked for errors. Additionally, there's no way for the programmer to detect if the operation has failed (maybe changing the return type?).

**Comment by guruofquality** [comment]
Not a bad idea, what do you think of: https://github.com/pothosware/SoapySDR/pull/174

**Comment by BatchDrake** [comment]
Perfect, this is exactly what I was looking for. Thanks!
