### ISSUE TITLE
Getter method SoapySDRKwargs_get is not treating SoapySDRKwargs as const

### ISSUE THREAD

**Issue by BatchDrake** [pothosware/SoapySDR#175]
https://github.com/pothosware/SoapySDR/blob/937131be31c1fad2859ddb9eb3ad90d813280b0a/lib/TypesC.cpp#L51

The prototype of this function implies that `args` may be altered by its implementation, however this is a lookup method/getter and therefore `args` should be read-only. How about changing it to `
const char *SoapySDRKwargs_get(const SoapySDRKwargs *args, const char *key)` ?

**Comment by guruofquality** [comment]
@BatchDrake Just an oversight, other calls have constness for their getters. I added this to the other C fix pull request: https://github.com/pothosware/SoapySDR/pull/174
