### ISSUE TITLE
Full duplex using Soapy?

### ISSUE THREAD

**Issue by dmitryelj** [pothosware/SoapySDR#180]
Hi all,
    
I am making antenna analyser application using UHD/USPR, so I need to simultaneously transmit data and analyse the response. What is the proper way to do it using Python and SoapySDR? I tried single threaded calls sdr.writeStream and then sdr.readStream, but I see 'UUU' in console and gaps in a data flow.
    
So, what is a correct way to do this? Are sdr.writeStream and sdr.readStream blocking when work? Can I use it from different threads at the same time? 

It would be nice if full duplex test will be added to the sample apps.
    
Thanks for the cool product, and best regards.

**Comment by guruofquality** [comment]
You can use the same thread if the overhead permits, or use different threads per each stream. Thread per stream is pretty common. The only thing you cant do is use the exact same stream from different threads at the same time. Also keep in mind, python is going to be slow compared to a C++/C implementation. So you might be limited by the python interpreter.

**Comment by dmitryelj** [comment]
Thanks for the answer. Now I adapted MeasureDelay.py to my needs - I send and receive signal at the same hardware time, it works.

Later I will test multithreading approach, and if it works, will publish it here.
