### ISSUE TITLE
make a release soon

### ISSUE THREAD

**Issue by ZeroChaos-** [pothosware/SoapySDR#186]
just a thought, been a while

**Comment by Toontje** [comment]
Please think about SdrDx integration as well?

**Comment by guruofquality** [comment]
The release is tagged and for SoapyRemote as well.

**Comment by ZeroChaos-** [comment]
bump, progress seems to have slowed a bit on this request.  I'd love to have this update in my livecd before the New Year :-)

**Comment by guruofquality** [comment]
All thats left is updating the PPA and tagging a few hardware support projects (if they merit it). Is there any project in particular you are looking for a new tag, etc?

**Comment by ZeroChaos-** [comment]
looks like soapybladerf, soapyplutosdr, soapyrtlsdr, soapysdrplay and to a lesser degree soapyuhd could all use an updated tag.  This is just based on my weak assessment that the changes since the last tag look meaningful in some way.

**Comment by guruofquality** [comment]
@ZeroChaos- I think everything has a tag now. Let me know if you need something else.

For anyone following, for the PPA I'm coordinating that on myriadrf FWIW: https://discourse.myriadrf.org/t/updating-the-ppa-to-soapysdr-0-7/3892

**Comment by guruofquality** [comment]
Final issue: updating the PPAs https://discourse.myriadrf.org/t/updating-the-ppa-to-soapysdr-0-7/3892

SoapySDR is up, working on other projects that depend on it now. Thanks!
