### ISSUE TITLE
Get wrong SDR when specifying serial

### ISSUE THREAD

**Issue by Heshyo** [pothosware/SoapySDR#191]
I'm not sure how much info we're supposed to provide when trying to connect to an SDR. Simply passing the `index` or `driver` and `index` may not be convenient if you have several boards.

I would have expected to be able to just specify the `serial` and get the proper board, but that's not the case.

With several Lime SDR connected, everything works as expected.

```
SoapySDRKwargs args = {};
SoapySDRKwargs_set(&args, "serial", limeSdrSerial);
sdr = SoapySDRDevice_make(&args);
SoapySDRKwargs_clear(&args);
```

But then if I connect a Lime Mini, it seems I always end up getting the Lime Mini, even when specifying the serial of a Lime SDR. Using the `driver` and `index` also always returns the Lime Mini.

Specifying both the `serial` and `module` fixes the problem:

```
SoapySDRKwargs args = {};
SoapySDRKwargs_set(&args, "module", "FX3");
SoapySDRKwargs_set(&args, "serial", limeSdrSerial);
sdr = SoapySDRDevice_make(&args);
SoapySDRKwargs_clear(&args);
```

But then if I plug a Blade RF 2, I can properly get 2 of my Lime SDR, but when trying to access the 3rd one with both `module` and `serial`, I'm getting the Blade RF 2 (this was tested with a very recent version of Pothos).

Adding the `driver` fixes the problem:

```
SoapySDRKwargs args = {};
SoapySDRKwargs_set(&args, "driver", "lime");
SoapySDRKwargs_set(&args, "module", "FX3");
SoapySDRKwargs_set(&args, "serial", limeSdrSerial);
sdr = SoapySDRDevice_make(&args);
SoapySDRKwargs_clear(&args);
```

I would expect the `serial` to be pretty unique, even between brands, so it would be nice to be able to just specify that.

**Comment by guruofquality** [comment]
You should be fine with specifying only driver, and one unique identifier like serial. "driver" is special in that it actually is used inside of SoapySDR to filter out specific support modules. The rest of the keys are just passed on to be interpreted as the support module pleases.

You are right in that you should be able to do this with only serial, but some of the support modules wont respect that, and they will not be filtered out. But in the case of only installing support modules with serial, then this should work.

So I suspect there is an issue in SoapyBladeRF in regards to filtering based on serial: https://github.com/pothosware/SoapyBladeRF/blob/master/bladeRF_Registation.cpp#L81 Or libbladerf itself has a bug in the bladerf_devinfo_matches() implementation.

**Comment by Heshyo** [comment]
Thanks Josh, so I'll just specify the `driver` and `serial`.

**Comment by guruofquality** [comment]
I left an open bug on soapybladerf since it sounds like there is a problem: https://github.com/pothosware/SoapyBladeRF/issues/23
