### ISSUE TITLE
WIKI Build Gude Update.

### ISSUE THREAD

**Issue by tdbone1** [pothosware/SoapySDR#194]
i have successfully built SoapySdr and Pothos LimeSuite from git using Kali-linux i386.
i was just wondering what do you do when git has updates and you want to update your binaries you already have installed.
do you have to 'make clean' and remove any files manually
it would be nice to add how to properly updating from git after you have successfully built (according to the wiki build guide.)

**Comment by guruofquality** [comment]
For 99% of these projects, updating is basically
```
cd source_directory; git pull
cd build_directory; make && sudo make install
#and for debian based distros, they make need sudo ldconfig if the library bumped so numbes
```

**Comment by guruofquality** [comment]
I added a note in the unix build instructions: https://github.com/pothosware/SoapySDR/wiki/BuildGuide#unix-instructions
