### ISSUE TITLE
Simulate USRP in gnuradio

### ISSUE THREAD

**Issue by Zarados** [pothosware/SoapySDR#197]
Hi, I used SoapySDR that LimeSDR simulate USRP.

uhd_find_devices and uhd_usrp_probe can find LimeSDR.

If I want to use LimeSDR simulate USRP in gnuradio, what should i do to change in the UHD source block?

I have tried to add "type=soapy" or "serial =xxxxxxx"  in the "Device Address"  of the UHD source block,but the gnuradio still not found the device.

What should I do to fix this error?

Thank you!!

**Comment by guruofquality** [comment]
> uhd_find_devices and uhd_usrp_probe can find LimeSDR.

Thats a good sign

Can you share the result of uhd_find_devices?

> I have tried to add "type=soapy" or "serial =xxxxxxx" in the "Device Address" of the UHD source block,but the gnuradio still not found the device.

Can you use the exact same arguments from uhd_find_devices? Maybe some arguments are different

Also make sure that gr-uhd was compiled from the same UHD development files as SoapyUHD. Just a guess, but if there was some different copy of libuhd for development, maybe one from a debian package, might cause some confusion.

**Comment by Zarados** [comment]
> > uhd_find_devices and uhd_usrp_probe can find LimeSDR.
> 
> Thats a good sign
> 
> Can you share the result of uhd_find_devices?
> 
> > I have tried to add "type=soapy" or "serial =xxxxxxx" in the "Device Address" of the UHD source block,but the gnuradio still not found the device.
> 
> Can you use the exact same arguments from uhd_find_devices? Maybe some arguments are different
> 
> Also make sure that gr-uhd was compiled from the same UHD development files as SoapyUHD. Just a guess, but if there was some different copy of libuhd for development, maybe one from a debian package, might cause some confusion.

Thanks for your reply.

I use SoapySDR that HackRF simulate USRP now.

SoapySDRUtil --find
https://imgur.com/a/YSySq9C

uhd_find_devices
https://imgur.com/a/ywfxTpO

uhd_usrp_probe
https://imgur.com/a/CWMbEgn

gnuradio not found device 
https://imgur.com/a/TQthXyq

Thank you!!

**Comment by Zarados** [comment]
I build uhd from source with SoapySDR.

And I remove uhd-host from Kali Linux, but this error still exists.

**Comment by guruofquality** [comment]
> And I remove uhd-host from Kali Linux, but this error still exists.

The runtime libraries could still be installed. 

I think using UHD from the package manager is fine, but you need to also build SoapyUHD from the development files from the package manager.

**Comment by Zarados** [comment]
I have build SoapyUHD from the source.

Should I install SoapySDR hardware package and SoapySDR runtime package from the package manager, not from the source?

**Comment by guruofquality** [comment]
Ultimately you have a lot of freedom here. I don't really know what you did or didnt install from source or from packages, so I can just give some general advice. Its really the same advice for any c-style packages.

* https://github.com/pothosware/SoapySDR/wiki/ConfigGuide#when-to-build-from-source

And I suspect that you installed multiple copies of libuhd. One from the package manager that is pulled in by gnuradio and another from source. So that would probably be the source of the issue. If you have a good copy of uhd in the package manager that works for you, dont install it from source. And certainly don't do both.

* https://github.com/pothosware/SoapySDR/wiki/ConfigGuide#avoid-simultaneous-installs

**Comment by Zarados** [comment]
I'm try again with a new kali virtual machine.

And SoapySDRUtil can find hackrf, but uhd_find_devices can't.

I install SoapySDR from packages.

Did you have any idea? Thank you!!

SoapySDRUtil --find
https://imgur.com/a/HhZFSyu

uhd_find_devices
https://imgur.com/a/6t0Nr0J

apt list --installed | grep soapy
https://imgur.com/a/agiA8Re

apt list --installed | grep uhd
https://imgur.com/a/wbwxbbo

**Comment by guruofquality** [comment]
Did you see the notes about UHD_MODULE_PATH? https://github.com/pothosware/SoapyUHD/wiki#soapy-devices-in-uhd

Find where libsoapySupport.so is installed and make sure its in the environment variable UHD_MODULE_PATH. The file is usually installed to `${UHD_ROOT}/lib${LIB_SUFFIX}/uhd/modules` where UHD_ROOT is the install prefix for uhd. -- Really the only trick to making this work is to get uhd to load this file: libsoapySupport.so

And do report back where the files are installed, thanks
