### ISSUE TITLE
Icom ICR support (enchancement)

### ISSUE THREAD

**Issue by dmitryelj** [pothosware/SoapySDR#198]
Hi all,

I am happy to announce that I've finished beta version of the SoapySDR library for Icom IC-R8600 receiver.
https://github.com/dmitryelj/SoapyICR8600

Will be nice to add it to the pothosware page as well.

**Comment by guruofquality** [comment]
Cool! Thats great. I added a link in the side bar, and if you ever want to host it on this github organization, let me know!
