### ISSUE TITLE
OpenLTE with soapyUHD

### ISSUE THREAD

**Issue by Dastgsm** [pothosware/SoapySDR#205]
I'm trying openlte with soapyUHD and i have this error! 
UHD Error: Tx Calibration: MCU error 5 (Loopback signal weak: not connected/insufficient gain?) – Rx calibration finished  UHD Warning: popping from TX, samples popped 540/1020.

any idea to fix it ?

**Comment by Dastgsm** [comment]
Note that i use limesdrmini.

**Comment by Dastgsm** [comment]
so to have best IQ balance or DC , the Tx send calibration to the Rx and SoapySDR try to see how to have a best synchronisation with ?

**Comment by guruofquality** [comment]
The LimeSDR calls calibration when the stream is activated: https://github.com/myriadrf/LimeSuite/blob/master/SoapyLMS7/Streaming.cpp#L203

If you think something is wrong or you have a support question, you need to ask the maintainers:

* https://github.com/myriadrf/LimeSuite
* https://discourse.myriadrf.org/
