### ISSUE TITLE
Crash when using rx_power

### ISSUE THREAD

**Issue by dropdrop20** [pothosware/SoapySDR#210]
root@XXXXXXXXXXXX:~ # rx_power -f 150M:160M:2k  -i 5s -e 300 survey.csv
Number of frequency hops: 4
Dongle bandwidth: 2500000Hz
Downsampling by: 1x
Cropping by: 0.00%
Total FFT bins: 8192
Logged FFT bins: 8192
FFT bin size: 1220.70Hz
Buffer size: 16384 bytes (3.28ms)
Reporting every 5 seconds
Using device 18070ED596: mir_sdr_api_version=2.130000 mir_sdr_hw_version=255 remote:version=0.5.1-g5a647db9
Found 1 channel(s) :
Channel 0 :
  Found 1 antenna(s): RX
  Found 2 gain(s): IFGR RFGR
  Found 2 frequencies: RF CORR
  Found 13 sample rates: 250000 500000 1000000 2000000 2048000 3000000 4000000 5000000 6000000 7000000 8000000 9000000 10000000
  Found 8 bandwidths: 200000 300000 600000 1536000 5000000 6000000 7000000 8000000
Invalid channel selected (num_channels=1)
Segmentation fault

root@XXXXXXXXXXX:~ # gdb  /usr/local/bin/rx_power core
GNU gdb (Raspbian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/rx_power...(no debugging symbols found)...done.
[New LWP 5450]
[New LWP 5430]
[New LWP 5440]
[New LWP 5448]
[New LWP 5443]
[New LWP 5449]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Core was generated by `rx_power -f 88M:102M:100k -i 10s -1 survey.csv'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x767edb5c in SoapySDRPlay::rx_callback(short*, short*, unsigned int) () from /usr/local/lib/SoapySDR/modules0.7/libsdrPlaySupport.so
[Current thread is 1 (Thread 0x743e7050 (LWP 5450))]
(gdb) bt
#0  0x767edb5c in SoapySDRPlay::rx_callback(short*, short*, unsigned int) () from /usr/local/lib/SoapySDR/modules0.7/libsdrPlaySupport.so
#1  0x74c417c0 in StreamReadThread () from /usr/local/lib/libmirsdrapi-rsp.so.2.13
#2  0x743e7050 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by guruofquality** [comment]
Looks like this got fixed
