### ISSUE TITLE
Recent C setup stream API change breaks backward compatibility

### ISSUE THREAD

**Issue by szpajder** [pothosware/SoapySDR#215]
The change implemented in https://github.com/pothosware/SoapySDR/pull/212 is described as being backward compatible, while in fact, it's not.

```C
{
    *stream = SoapySDRDevice_setupStream(device, direction, format, channels, numChans, args);
    return (stream == NULL)?0:-1;
}
```

Before that, `SoapySDRDevice_setupStream()` returned 0 on success and -1 on failure. Now it's exactly the opposite.

**Comment by guruofquality** [comment]
Thanks, I pushed a fix!
