### ISSUE TITLE
Parallel Make/Unmake in C API

### ISSUE THREAD

**Issue by twuillemin** [pothosware/SoapySDR#217]
In Device.h, we have:
```c
SOAPY_SDR_API SoapySDRDevice **SoapySDRDevice_make_list([...])
SOAPY_SDR_API int SoapySDRDevice_unmake_list([...])
```

However, in FactoryC.cpp, functions are named:
```c
SoapySDRDevice **SoapySDRDevice_make_each([...])
int SoapySDRDevice_unmake_each([...])
```

Making them a bit inaccessible.

Fix is easy, but what name should we keep ?

**Comment by guruofquality** [comment]
Thanks, I bet that was a last-minute rename before I made the commit. I missed that: https://github.com/pothosware/SoapySDR/commit/3f3f012f2ea02f682f293ca3c710c58698186fec Fix will me merged into master in a bit
