### ISSUE TITLE
SoapySDRDevice_readStream returned -6: TIME_ERROR

### ISSUE THREAD

**Issue by BilalMaqsood88** [pothosware/SoapySDR#223]
Hi SoapySDR Team,

I am using soapySDR with srsLTE (https://github.com/srsLTE/srsLTE) to access the LimeSDR usb. While running the srsUE, I recieve this error, can you please let me know the cause and it will be great if you suggest what could be done.  
 
SoapySDRDevice_readStream returned -6: TIME_ERROR

Thanks and Regards,
Bilal

**Comment by guruofquality** [comment]
My guess is that the application is passing a time to activateStream() that is less than the current time on the device.

**Comment by BilalMaqsood88** [comment]
Thanks for the reply. Any idea how to fix this ?

**Comment by guruofquality** [comment]
Put some debug prints into srsLTE, and try to figure out why they are requesting late timestamps. If srsLTE is fine, but it appears to be a bug in LimeSuite, try to make a test case to show the failure so the folks at Lime Micro can fix it - https://github.com/myriadrf/LimeSuite/issues
