### ISSUE TITLE
cannot run C_API_EXAMPLE on ubuntu 18.04

### ISSUE THREAD

**Issue by AnouarNechi** [pothosware/SoapySDR#224]
Hi I installed soapySDR to use it with the LimeSDR USB, i found the C_API_EXAMPLE and i wanted to try it but I keep getting this error 

  $ gcc -std=c99 API_example.c -lSoapySDR && ./a.out
  API_example.c:1:10: fatal error: SoapySDR/Device.h: No such file or directory
  #include <SoapySDR/Device.h>

when I test the soapySDRUTIL commands it seems fine:

$ SoapySDRUtil --info
######################################################
######################################################

Lib Version: v0.7.1-myriadrf1~ubuntu18.04
API Version: v0.7.1
ABI Version: v0.7
Install root: /usr
Search path:  /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7
Search path:  /usr/local/lib/x86_64-linux-gnu/SoapySDR/modules0.7   (missing)
Search path:  /usr/local/lib/SoapySDR/modules0.7                    (missing)
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/libLMS7Support.so (19.01.0)   
Available factories... lime
Available converters...
-  CF32 -> [CF32, CS16, CS8, CU16, CU8]
-  CS16 -> [CF32, CS16, CS8, CU16, CU8]
-  CS32 -> [CS32]
-   CS8 -> [CF32, CS16, CS8, CU16, CU8]
-  CU16 -> [CF32, CS16, CS8]
-   CU8 -> [CF32, CS16, CS8]
-   F32 -> [F32, S16, S8, U16, U8]
-   S16 -> [F32, S16, S8, U16, U8]
-   S32 -> [S32]
-    S8 -> [F32, S16, S8, U16, U8]
-   U16 -> [F32, S16, S8]
-    U8 -> [F32, S16, S8]

could someone help me please?

**Comment by guruofquality** [comment]
Read the section titled "Attention debian/ubuntu/PPA users" https://github.com/pothosware/SoapySDR/wiki/ConfigGuide#when-to-build-from-source
