### ISSUE TITLE
Windows file separators incorrect in several places

### ISSUE THREAD

**Issue by MarcKaufman** [pothosware/SoapySDR#227]
There are several places in Modules.cpp where the incorrect separator is used. Here are my patches:

SoapySDR::listSearchPaths
    searchPaths.push_back(SoapySDR::getRootPath() + 
#ifdef _MSC_VER
		"\\\\lib\\SoapySDR\\\\modules"
#else
		"/lib/SoapySDR/modules"
#endif
		+ SoapySDR::getABIVersion());

SoapySDR::listModules
   return searchModulePath(path + 
#ifdef _MSC_VER
		"\\\\"
#else
		"/"
#endif
	); //requires trailing slash

**Comment by guruofquality** [comment]
Most command lines don't allow "/" because it conflicts with the use of "/" for a switch delimiter. But the Windows and DOS kernels are happy with either "\" or "/". So something isnt broken, this is just aesthetic right?

**Comment by MarcKaufman** [comment]
Nothing to do with the command line. getRootPath and listModules are used for finding the dlls to load. If you don't do the change you get "/" in Windows paths, which doesn't work. I was chasing a bug where SDRPlaySupport wouldn't load in CubicSDR. Cubic was giving Soapy a path ending in "\\\\", which then had a "/" appended, making file search unworkable. I'll try taking out the Soapy changes one at a time now that I have the file search running correctly.

**Comment by MarcKaufman** [comment]
I just checked with the other delimiters. Works fine. Sorry for the false bug report.
