### ISSUE TITLE
readStream failed: OVERFLOW

### ISSUE THREAD

**Issue by dupilax** [pothosware/SoapySDR#236]
Hello

Since this morning, after an upgrade of SoapySDR I got this error with the SoapyAirspyHF module : SoapySDR device 'driver=airspyhf,device_id=0': readStream failed: OVERFLOW, disabling

I try to revert to previous version but still got the error...

What does this mean ?
Is there any way to get rid of this error ?
It appear less than two minutes after launching the program...

Thanks

**Comment by guruofquality** [comment]
Duplicate: https://github.com/pothosware/SoapyAirspyHF/issues/11
