### ISSUE TITLE
Distribute SoapySDR with pip?

### ISSUE THREAD

**Issue by gasparka** [pothosware/SoapySDR#240]
It would be super convenient if Soapy could be installed from pip.  I know it is not that simple because C code involved, but it is definitely doable. 
Wondering if anyone has experimented with this? And if @guruofquality sees this as something worth having.

**Comment by guruofquality** [comment]
Sure, not sure how this would or should work with the hardware support modules. But it seems like a reasonable idea. More packaging options are good. looking for volunteers :-P

**Comment by gasparka** [comment]
I might be playing around with this. Lime support looks doable because no hardware support module is required.
Also SoapySDR-Remote could work well over pip.
