### ISSUE TITLE
build within the Conda environment

### ISSUE THREAD

**Issue by vielmetti** [pothosware/SoapySDR#251]
I'm building from source, and I'd like the Python environment to be the one provided by `conda`, rather than the system Python.

#240 (install with pip) would handle this directly, but perhaps someone is familiar with conda/Anaconda and could point out something obvious.

This is motivated by https://github.com/rapidsai/cusignal/blob/master/notebooks/sdr_wfm_demod.ipynb - a Jupyter notebook for SDR .

**Comment by guruofquality** [comment]
Hopefully resolved by https://github.com/conda-forge/soapysdr-feedstock

* related https://github.com/pothosware/SoapySDR/issues/289
