### ISSUE TITLE
Cannot find device string needed for Satnogs reception for Adalm Pluto

### ISSUE THREAD

**Issue by zanco** [pothosware/SoapySDR#258]
Hi, running a Raspberry Pi 4, SoapySDR for the Adalm Pluto installed succesfully. 
`pi@raspberrypi:~ $ SoapySDRUtil --find
######################################################
######################################################

Found device 0
  device = plutosdr
  driver = plutosdr
  uri = usb:1.3.5
`
the command SoapySDRUtil --probe="driver=plutosdr,hostname=192.168.2.1" outputs a complete list if adc voltages, RX channel 0 and TX channel 0 information. Can run the Pluto as remote server device on the Pi 4 and connect to it from SoapySDR on a WIndows machine. So far so good.

Now I am trying to get the Pluto in the Satnogs setup. Satnogs makes use of the SoapySDR devices, but I can not make the Pluto to work. 

Tried:
driver=plutosdr
driver=pluto
dirver=plutosdr,hostname=192.168.2.1
driver=plutosdr,uri=usb:1.3.5

All resulting in: 

`RuntimeError: SoapySDR::Device::make() no match
Apr 17 13:57:14 raspberrypi satnogs-client[10087]: satnogsclient.observer.observer - ERROR - No waterfall data file found`

Can anyone help me with this ?

Thanks,
Ben

**Comment by guruofquality** [comment]
Closing old issue. But in the future, the https://github.com/pothosware/SoapyPlutoSDR/issues might be more helpful
