### ISSUE TITLE
Missing module, manual build raspberry pi 4

### ISSUE THREAD

**Issue by thecyberdotninja** [pothosware/SoapySDR#262]
**So end goal is to use HackRF on raspberry pi 4, I get the following:**

`pi@raspberrypi:~/SoapySDR/build $ SoapySDRUtil --find
######################################################
     Soapy SDR -- the SDR abstraction library     
######################################################

No devices found!
`
**This is how I built it:**

`SoapySDR/build $ cmake ..
-- Build type not specified: defaulting to release.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
--
-- #############################################
--  Begin configuration for Python support...
-- #############################################
-- Enabling optional Python bindings if possible...
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
-- SWIG_FOUND: FALSE -
-- PYTHONINTERP_FOUND: TRUE - 2.7.16
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_INSTALL_DIR: ${prefix}/lib/python2.7/dist-packages
-- PYTHONLIBS_FOUND: TRUE - 2.7.16
-- PYTHON_INCLUDE_DIRS: /usr/include/python2.7;/usr/include/arm-linux-gnueabihf/python2.7
-- PYTHON_LIBRARIES: -L/usr/lib/python2.7/config-arm-linux-gnueabihf -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
--
-- #############################################
--  Begin configuration for Python3 support...
-- #############################################
-- Enabling optional Python3 bindings if possible...
-- Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
-- SWIG_FOUND: FALSE -
-- Could NOT find Python3InterpDbg (missing: PYTHON3_DBG_EXECUTABLE)
-- PYTHON3INTERP_FOUND: TRUE
-- PYTHON3_EXECUTABLE: /usr/bin/python3
-- PYTHON3_INSTALL_DIR: ${prefix}/lib/python3.7/dist-packages
-- PYTHON3LIBS_FOUND: TRUE
-- PYTHON3_INCLUDE_DIRS: /usr/include/python3.7m;/usr/include/python3.7m
-- PYTHON3_LIBRARIES: -L/usr/lib/python3.7/config-3.7m-arm-linux-gnueabihf -L/usr/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
--
-- ######################################################
--  SoapySDR enabled features
-- ######################################################
--
 * Library, runtime library v0.8.0-gf722f9ce
 * Apps, command line applications
 * Tests, library unit tests

-- ######################################################
--  SoapySDR disabled features
-- ######################################################
--
 * Docs, doxygen documentation
 * Python, python bindings v2.7.16
 * Python3, python3 bindings

-- SoapySDR version: v0.8.0-gf722f9ce
-- ABI/so version: v0.8
-- Install prefix: /usr/local
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/SoapySDR/build
pi@raspberrypi:~/SoapySDR/build $ make
[ 64%] Built target SoapySDR
[ 76%] Built target SoapySDRUtil
[ 82%] Built target TestFormatParser
[ 88%] Built target TestKwargsMarkup
[ 94%] Built target TestTimeConversion
[100%] Built target TestConvertTypes
pi@raspberrypi:~/SoapySDR/build $ sudo make install
[ 64%] Built target SoapySDR
[ 76%] Built target SoapySDRUtil
[ 82%] Built target TestFormatParser
[ 88%] Built target TestKwargsMarkup
[ 94%] Built target TestTimeConversion
[100%] Built target TestConvertTypes
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /usr/local/share/cmake/SoapySDR/SoapySDRConfig.cmake
-- Up-to-date: /usr/local/share/cmake/SoapySDR/SoapySDRUtil.cmake
-- Up-to-date: /usr/local/share/cmake/SoapySDR/SoapySDRConfigVersion.cmake
-- Up-to-date: /usr/local/include/SoapySDR
-- Up-to-date: /usr/local/include/SoapySDR/Config.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Logger.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Errors.h
-- Up-to-date: /usr/local/include/SoapySDR/Version.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Errors.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Types.h
-- Up-to-date: /usr/local/include/SoapySDR/Formats.h
-- Up-to-date: /usr/local/include/SoapySDR/Logger.h
-- Up-to-date: /usr/local/include/SoapySDR/Device.hpp
-- Up-to-date: /usr/local/include/SoapySDR/ConverterPrimitives.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Modules.h
-- Up-to-date: /usr/local/include/SoapySDR/Time.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Time.h
-- Up-to-date: /usr/local/include/SoapySDR/ConverterRegistry.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Device.h
-- Up-to-date: /usr/local/include/SoapySDR/Registry.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Types.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Config.h
-- Up-to-date: /usr/local/include/SoapySDR/Constants.h
-- Up-to-date: /usr/local/include/SoapySDR/Version.h
-- Up-to-date: /usr/local/include/SoapySDR/Modules.hpp
-- Up-to-date: /usr/local/include/SoapySDR/Formats.hpp
-- Up-to-date: /usr/local/lib/libSoapySDR.so.0.8.0
-- Up-to-date: /usr/local/lib/libSoapySDR.so.0.8
-- Up-to-date: /usr/local/lib/libSoapySDR.so
-- Up-to-date: /usr/local/share/cmake/SoapySDR/SoapySDRExport.cmake
-- Installing: /usr/local/share/cmake/SoapySDR/SoapySDRExport-release.cmake
-- Up-to-date: /usr/local/lib/pkgconfig/SoapySDR.pc
-- Up-to-date: /usr/local/bin/SoapySDRUtil
-- Up-to-date: /usr/local/share/man/man1/SoapySDRUtil.1
pi@raspberrypi:~/SoapySDR/build $ sudo ldconfig
pi@raspberrypi:~/SoapySDR/build $ SoapySDRUtil --info
######################################################
######################################################

Lib Version: v0.8.0-gf722f9ce
API Version: v0.8.0
ABI Version: v0.8
Install root: /usr/local
Search path:  /usr/local/lib/SoapySDR/modules0.8 (missing)
No modules found!
Available factories... No factories found!
Available converters...
 -  CF32 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS16 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS32 -> [CS32]
 -   CS8 -> [CF32, CS16, CS8, CU16, CU8]
 -  CU16 -> [CF32, CS16, CS8]
 -   CU8 -> [CF32, CS16, CS8]
 -   F32 -> [F32, S16, S8, U16, U8]
 -   S16 -> [F32, S16, S8, U16, U8]
 -   S32 -> [S32]
 -    S8 -> [F32, S16, S8, U16, U8]
 -   U16 -> [F32, S16, S8]
 -    U8 -> [F32, S16, S8]

`
**Thoughts on how to correct?**

**Comment by guruofquality** [comment]
install https://github.com/pothosware/SoapyHackRF/wiki
