### ISSUE TITLE
SoapySDRDevice_enumerate causing a memory leak

### ISSUE THREAD

**Issue by cthouck31** [pothosware/SoapySDR#280]
I'm working on an application and I noticed that 'SoapySDRDevice_enumerate(...)" seems to be giving me a memory leak.

I initially thought I was using the function incorrectly, so I tried to verify the issue using valgrind on the 'SoapySDRUtil' utility:
```bash
valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all -v SoapySDRUtil --find
```
The output is in the attached file:
[SoapySDRUtil_valgrind.log](https://github.com/pothosware/SoapySDR/files/5462623/SoapySDRUtil_valgrind.log)

I compiled SoapySDR from source using the recommended dependencies:
```bash
cmake -DCMAKE_BUILD_TYPE=Debug ..
```
[SoapySDR_cmake.log](https://github.com/pothosware/SoapySDR/files/5462632/SoapySDR_cmake.log)

I added a few print statements to see where the leak was coming from and found that the 'dlclose' function isn't called on exit (near Modules.cpp:302).

I noticed the futures with a cache timeout of 1 second (program exits in <1 second), but not being well versed in the use of futures I didn't pursue this. Just thought I'd mention it in case it helps.

OS: 18.04.5 LTS (Bionic Beaver)
Kernel: 4.15.0-122-generic

Let me know if you need more details, I'm happy to help where I can.

**Comment by guruofquality** [comment]
I'm not so worried about the c++ objects, they tend to clean up nicely, but it looks like you are right; there is no attempt to unload the modules which leaks memory and may also stop the modules from doing their own unloads. I will need to make the unloads automatic on library unload.

It also looks like some modules themselves may have their own memory leaks. For example the avahi support for SoapyRemote seems to do so.
