### ISSUE TITLE
XTRX Driver Support

### ISSUE THREAD

**Issue by RFNOD** [pothosware/SoapySDR#284]
Hi All,

Is anyone gotten the XTRX from Fairwaves to work with Soapy? If not, I can try and figure it out and build a driver for Soapy using this guide: https://github.com/pothosware/SoapySDR/wiki/DriverGuide. I didn't want to reinvent the wheel and wanted to ask first. Thanks!!

**Comment by guruofquality** [comment]
Maybe it needs a link on the main panel, but give this https://github.com/xtrx-sdr/libxtrx/tree/master/soapy a try

**Comment by RFNOD** [comment]
Will do. Thanks!!

**Comment by hewittc** [comment]
I was only able to get their module to work after making a quick [patch](https://github.com/xtrx-sdr/libxtrx/issues/27). Without the patch, `SoapyXTRX::activateStream` wouldn't allow opening an RX stream. I can't determine if the developers are monitoring that repository or plan to provide any additional support or development for that module, though.

**Comment by rfwill202** [comment]
Can you submit a PR? I can reach out to a maintainer of that repo. And they should be able to merge it.

**Comment by RFNOD** [comment]
@hewittc Can you submit a PR? I can reach out to a maintainer of that repo. And they should be able to merge it. Thanks!!

**Comment by RFNOD** [comment]
https://github.com/xtrx-sdr/libxtrx/pull/30 was merged.. Thanks @hewittc !!!!

**Comment by RFNOD** [comment]
So, how do we add it to the SoapySDR supported devices list? Let me know what needs to be done and I can do it.

**Comment by guruofquality** [comment]
> So, how do we add the XTRX to the SoapySDR supported devices list/sidebar? Let me know what needs to be done and I can do it.

I edited the wiki
