### ISSUE TITLE
Build fails on macOS Big Sur

### ISSUE THREAD

**Issue by ik2wxx** [pothosware/SoapySDR#298]
Hello all
Build fails on macOS Big Sur.
I'm following info at https://github.com/pothosware/homebrew-pothos/wiki

brew tap dholm/homebrew-sdr

==> Tapping dholm/sdr
Cloning into '/usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr'...
remote: Enumerating objects: 441, done.
remote: Total 441 (delta 0), reused 0 (delta 0), pack-reused 441
Receiving objects: 100% (441/441), 120.77 KiB | 477.00 KiB/s, done.
Resolving deltas: 100% (269/269), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr/multimon-ng.rb
multimon-ng: Unsupported special dependency :x11
Error: Cannot tap dholm/sdr: invalid syntax in tap!

Also other commands end with error.
Does the info need to be updated ?

**Comment by guruofquality** [comment]
there is an open issue here: https://github.com/dholm/homebrew-sdr/issues/41

**Comment by ersingencturk** [comment]
same here too:

```
Tapping dholm/sdr
Cloning into '/usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr'...
remote: Enumerating objects: 441, done.
remote: Total 441 (delta 0), reused 0 (delta 0), pack-reused 441
Receiving objects: 100% (441/441), 120.77 KiB | 1.04 MiB/s, done.
Resolving deltas: 100% (269/269), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/dholm/homebrew-sdr/multimon-ng.rb
multimon-ng: Unsupported special dependency :x11
Error: Cannot tap dholm/sdr: invalid syntax in tap!

```
