### ISSUE TITLE
[low-priority] Swig compile failure

### ISSUE THREAD

**Issue by xloem** [pothosware/SoapySDR#306]
after `cmake ..` on git master today:
```
[ 94%] Swig compile /home/user/src/SoapySDR/build/python/SoapySDR.i for python
/home/user/src/SoapySDR/build/python/SoapySDR.i:38: Error: Syntax error in input(1).
```

I tried some old tags.  The error is not present for me in 0.7.0, and was introduced before 0.8.0 .  I have swig 2.0.10 .

**Comment by guruofquality** [comment]
Looks related to the %pythonbegin %{ ... %} section. Perhaps its a swig 3.0 thing. I can add a version check but im not 100% sure thats the reason. Do you have a version of swig3.0 in the package manager to try, for example ubuntu is `apt-get install swig3.0`

**Comment by guruofquality** [comment]
FYI `pythonbegin` was added in `Version 2.0.11 (15 Sep 2013)` http://swig.org/Release/CHANGES

**Comment by marcusmueller** [comment]
To be honest, I remember Ubuntu 14.04 already shipping swig 2.0.11, and everything after that shipped swig 3.0 or later at will. Any system that's more antiquated than that is probably not worth porting new software to.

**Comment by guruofquality** [comment]
One alternative to the version check would be to add swig ifdefs around the `pythonbegin` section using SWIG_VERSION http://www.swig.org/Doc4.0/Preprocessor.html

**Comment by xloem** [comment]
it is humorous that for a year and a half three of us chose to discuss and postpone this rather than simply patching a one line fix. ncorgan figured this out.
