### ISSUE TITLE
StringToSetting<bool> Incorrect Return Type

### ISSUE THREAD

**Issue by AtaraxyApps** [pothosware/SoapySDR#308]
The issue resides in the `types.hpp::StringToSetting<bool>()`
See [line](https://github.com/pothosware/SoapySDR/blob/3fa5ef7437983ae3e6a4d3cf6eb31438c95794c6/include/SoapySDR/Types.hpp#L185). Function copied below:

```c++
template <typename Type>
typename std::enable_if<std::is_same<Type, bool>::value, Type>::type StringToSetting(const std::string &s)
{
    if (s == SOAPY_SDR_TRUE) return true;
    if (s == SOAPY_SDR_FALSE) return false;

    //zeros and empty strings are false
    if (s == "0") return false;
    if (s == "0.0") return false;
    if (s == "") return false;

    //other values are true
    return "true";
}
```

The last return statement should be `true`. Luckily if that line is reached right now it will eventually evaluate to true anyways.

**Comment by guruofquality** [comment]
thanks https://github.com/pothosware/SoapySDR/commit/5bcb611bfd20efbeb0cd3ad559368a7603f83291
