### ISSUE TITLE
Soapy_power with SDRPlay RSP1A | No devices found 

### ISSUE THREAD

**Issue by Nekxoo** [pothosware/SoapySDR#314]
Hi, I have install all Dependencies, when I execute SoapySDRUtil --find"sdrplay" he show my device, but when I execute the program soapy_power, he don't find my devices.

Can you help me pls?
![image](https://user-images.githubusercontent.com/85612199/121482170-2b7ca600-c9cd-11eb-884b-1ee2da45eb50.png)

**Comment by righthalfplane** [comment]
@Nekxoo 

It is a bit late, but the likely problem is that you have two version Soapy installed. See if you find two versions-

sudo find / -name "*modules0.*"

If it find many copies of modules0.7 of modules0.8 that is your problem.

If that is not you problem a second possible solution is to use -d driver=sdrplay in your soapy_power line.
