### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by rodrirq** [pothosware/SoapySDR#316]
Hello, I am trying to cross-compile SoapySDR for ARM using PetaLinux SDK 2020.2
I get through the cmake, but during make I get the following error:

Scanning dependencies of target _SoapySDR
[ 90%] Building CXX object python/CMakeFiles/_SoapySDR.dir/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o
cc1plus: warning: include location "/usr/include/python2.7" is unsafe for cross-compilation [-Wpoison-system-directories]
cc1plus: warning: include location "/usr/include/x86_64-linux-gnu/python2.7" is unsafe for cross-compilation [-Wpoison-system-directories]
In file included from /usr/include/python2.7/Python.h:8,
                 from /home/rodrirq/SoapySDR/build/python/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx:175:
/usr/include/python2.7/pyconfig.h:24:12: fatal error: arm-linux-gnueabihf/python2.7/pyconfig.h: No such file or directory
   24 | #  include <arm-linux-gnueabihf/python2.7/pyconfig.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
python/CMakeFiles/_SoapySDR.dir/build.make:62: recipe for target 'python/CMakeFiles/_SoapySDR.dir/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o' failed
make[2]: *** [python/CMakeFiles/_SoapySDR.dir/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:405: recipe for target 'python/CMakeFiles/_SoapySDR.dir/all' failed
make[1]: *** [python/CMakeFiles/_SoapySDR.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

It says that it cannot find arm-linux-gnueabihf/python2.7/pyconfig.h, which I don't have. But I don't know what to do.
Any idea?

**Comment by guruofquality** [comment]
Is disabling python an option for you? It might be easier if you dont need python on the target device.

pass `-DENABLE_PYTHON3=OFF -DENABLE_PYTHON=OFF` to cmake
