### ISSUE TITLE
Travis CI needs to move to travis-ci.com

### ISSUE THREAD

**Issue by ncorgan** [pothosware/SoapySDR#324]
https://travis-ci.org/pothosware/SoapySDR

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by ncorgan** [comment]
Of course, unless we move over to Github Actions, which may be better

**Comment by zuckschwerdt** [comment]
Did you already sketch something with Actions? https://github.com/pothosware/SoapySDR/pull/319#issuecomment-877673047

**Comment by ncorgan** [comment]
Unfortunately, it fell by the wayside. I suppose this is new motivation.

**Comment by zuckschwerdt** [comment]
I know that too well ;) Maybe our build_check_job (CMake+Ninja/UnixMakefiles) and analyzer_check_job (Clang) can be a quick starting point: https://github.com/merbanan/rtl_433/blob/master/.github/workflows/check.yml
