### ISSUE TITLE
SDRPlay device drivers can not be installed 

### ISSUE THREAD

**Issue by glangsto** [pothosware/SoapySDR#333]
The installation links are circular referring to SDRPlay site which refers to pothosware site.  
It is not possible to load the SDRPlay Api for 3.07

Suggestions welcome.

Most welcome would be a complete raspberry pi OS installation with Gnuradio 3.8 and also SDRplay support.

Best regards

Glen

**Comment by fventuri** [comment]
Glen,
I think the best way to install SoapySDR + support for the SDRplay RSPs on Linux is to follow the instructions from the Wiki (https://github.com/pothosware/SoapySDRPlay3/wiki), that comprise of these three main steps:

- install the SDRplay API version 3.07 for Linux (see here: https://www.sdrplay.com/softwarehome/)
- install SoapySDR (see here: https://github.com/pothosware/SoapySDR/wiki/BuildGuide) - the important steps are:
  - install the required dependencies (https://github.com/pothosware/SoapySDR/wiki/BuildGuide#id2)
  - get the source code (https://github.com/pothosware/SoapySDR/wiki/BuildGuide#id5)
  - build and install (https://github.com/pothosware/SoapySDR/wiki/BuildGuide#id6)
 - install the SoapySDRPlay module (https://github.com/pothosware/SoapySDRPlay3):
   - detailed instructions here: https://github.com/pothosware/SoapySDRPlay3/wiki#building-soapy-sdr-play

As per the Raspberry Pi, I know SDRplay offers a pre-built Raspberry Pi image (see here: https://www.sdrplay.com/raspberry-pi-images/), but I don't think GNU Radio is part of that image.
Alternatively you may want to look at DragonOS_Pi64 (https://sourceforge.net/projects/dragonos-pi64/), which should have both support for SDRPlay (via the installer) and GNU Radio; I read about it, but I've never tried it personally.

Franco

**Comment by glangsto** [comment]
Hi Franco,

I’ve tried exactly what you describe below several times.

1) There is no way to actually get the  API version 3.07 for Linux
for a raspberry pi.

2) The SoapySDR code does seem to install fine.

3) Because step 1 does not work, step 3 does not.

***@***.***:~/SoapySDRPlay/build $ cmake ..
-- The CXX compiler identification is GNU 8.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not specified: defaulting to release.
-- libsdrplay not found.
CMake Error at CMakeLists.txt:16 (message):
  SDRplay development files not found...


-- Configuring incomplete, errors occurred!
See also "/home/pi/SoapySDRPlay/build/CMakeFiles/CMakeOutput.log".

So, I’d greatly appreciate anyone providing an entire PI OS with
SDRPlay support.

Thanks
Glen


Glen I Langston, Ph. D.
Galactic Astronomy Program Director
National Science Foundation
304-456-3032

**Comment by fventuri** [comment]
Glen,
SDRplay does have an API version 3.07 installer for Linux ARM 32-bit - you can find it here: https://www.sdrplay.com/software/SDRplay_RSP_API-ARM32-3.07.2.run

Unfortunately at this time I don't think they provide the SDRplay API for Linux ARM 64-bit (aka 'AArch64').

Franco

**Comment by glangsto** [comment]
Thanks
I’ve been trying to use the 64bit version.  Maybe that is why I was
not finding the API.  I’ll try the 32 bit version.

Best regards

Glen

Glen I Langston, Ph. D.
Galactic Astronomy Program Director
National Science Foundation
304-456-3032

**Comment by fventuri** [comment]
Glen,
this morning I picked up the Raspberry Pi 4, and I ran the following steps:
- download and install the latest version of Raspberry OS (11 - bullesye)
- update the packages (apt update; apt full-upgrade; reboot)
- install GNU Radio from the Raspberry OS repository: apt install gnuradio - fortunately GNU Radio hat comes with Raspberry OS is version 3.8.2.0, which I think is the one you want
- install cmake
- SoapySDR: git clone, build, install (see steps above)
- SDRplay API 3.07: download, and run the installer
- SoapySDRPlay: git clone, build, install (see steps above)
- gr-soapy: git clone, build, install

After that I tried running a simple GRC script (similar to the FM receiver example here: https://github.com/fventuri/gr-sdrplay3/blob/master/examples/FM-Receiver-SDRplay.grc), and I was able to listen to a local FM BC station.
I had to move the soapy Python module from '/usr/local/lib/python3/dist-packages' to '/usr/local/lib/python3.9/dist-packages' (not sure why it got installed in the wrong place TBH), but I think that was the only major fix I had to make.

Anyway, if you are having problems with your Raspberry Pi, and are interested in this 'image' (just a copy of the whole filesystem), please let me know; I can compress it and put it somewhere so you can try it there.

Franco

**Comment by Ta-2om** [comment]
> Glen, I think the best way to install SoapySDR + support for the SDRplay RSPs on Linux is to follow the instructions from the Wiki (https://github.com/pothosware/SoapySDRPlay3/wiki), that comprise of these three main steps:
> 
>     * install the SDRplay API version 3.07 for Linux (see here: https://www.sdrplay.com/softwarehome/)
> 
>     * install SoapySDR (see here: https://github.com/pothosware/SoapySDR/wiki/BuildGuide) - the important steps are:
>       
>       * install the required dependencies (https://github.com/pothosware/SoapySDR/wiki/BuildGuide#id2)
>       * get the source code (https://github.com/pothosware/SoapySDR/wiki/BuildGuide#id5)
>       * build and install (https://github.com/pothosware/SoapySDR/wiki/BuildGuide#id6)
> 
>     * install the SoapySDRPlay module (https://github.com/pothosware/SoapySDRPlay3):
>       
>       * detailed instructions here: https://github.com/pothosware/SoapySDRPlay3/wiki#building-soapy-sdr-play
> 
> 
> As per the Raspberry Pi, I know SDRplay offers a pre-built Raspberry Pi image (see here: https://www.sdrplay.com/raspberry-pi-images/), but I don't think GNU Radio is part of that image. Alternatively you may want to look at DragonOS_Pi64 (https://sourceforge.net/projects/dragonos-pi64/), which should have both support for SDRPlay (via the installer) and GNU Radio; I read about it, but I've never tried it personally.
> 
> Franco

Receive this while cmake runs:
**":36: error: ‘SDRPLAY_RSPdxR2_ID’ was not declared in this scope; did you mean ‘SDRPLAY_RSPdx_ID’?
   78 |       else if (rspDevs[i].hwVer == SDRPLAY_RSPdxR2_ID)
      |                                    ^~~~~~~~~~~~~~~~~~
      |                                    SDRPLAY_RSPdx_ID
make[2]: *** [CMakeFiles/sdrPlaySupport.dir/build.make:76: CMakeFiles/sdrPlaySupport.dir/Registration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/sdrPlaySupport.dir/all] Error 2
make: *** [Makefile:136: all] Error 2"**

have RSP1a und Linux Mint 22

Grateful for any help

**Comment by fventuri** [comment]
@Ta-2om - it looks like the instructions you have are old.

SoapySDRPlay requires the latest version of the SDRplay API (currently version 3.15) that you can download from here: https://www.sdrplay.com/api/ 

I just updated the Wiki with the link above, since before I just had a link to their home page.

Please let me know if you have any problems building it with the latest version of the SDRplay API.

Franco

**Comment by Ta-2om** [comment]
Dear Franco,

I'm really grateful to you. Solved the issue like a magician. Thanks a lot a lot.

TA2OM Ersoy
