### ISSUE TITLE
No modules (factories) found

### ISSUE THREAD

**Issue by beginnerRF** [pothosware/SoapySDR#334]
Hello! I build and install SoapySDR from "Build Guide" and when I try "SoapySDRUtil --find", I get the message that modules are missing:
...
**sergey@spc:/$ SoapySDRUtil --inf
######################################################
######################################################

Lib Version: v0.8.1-g6f97389b
API Version: v0.8.0
ABI Version: v0.8
Install root: /usr/local
Search path:  /usr/local/lib/SoapySDR/modules0.8
No modules found!
Available factories... No factories found!
Available converters...**
...

Where to get these modules? Did everything according to the instructions from "Build Guide"

**Comment by guruofquality** [comment]
Install the relevant project for your desired hardware. Example RTLSDR: https://github.com/pothosware/SoapyRTLSDR/wiki
