### ISSUE TITLE
Soapy Lime Transmit | Incorrect behavior of the gain variable

### ISSUE THREAD

**Issue by m-anish** [pothosware/SoapySDR#343]
Hi, I am trying out the Soapy-LimeSDR-sink block in GNURadio 3.9 and am noticing odd behavior of the actual transmitted power in relation to the Gain setting.

My settings are as follows:
1. Transmitting at 98MHz
2. GNURadio 0.9
3. Last git # of the soapy repo (6f97389b2ef5e0f2a2aa855320b1a12a4e3e55ad)
4. Using LimeUSB board
5. Linux Mint / Ubuntu 18.04 base OS

Now, I'm measuring output power at different gain settings, and while the variable behaves normally from -12 to 50, odd things start to happen after that.

The max tx power peaks at gain=55

The max tx power actually reduces and the value at gain=60 is actually much lower than the value at gain=55.

**Comment by zuckschwerdt** [comment]
The LimeSDR driver module for SoapySDR is called SoapyLMS7 and hosted at https://github.com/myriadrf/LimeSuite/tree/master/SoapyLMS7
The gain setting just passes the value to the LMS7 API: https://github.com/myriadrf/LimeSuite/blob/master/SoapyLMS7/Settings.cpp#L281-L287
I would recommend to test just the LMS7 API and trace what happens there, e.g. https://github.com/myriadrf/LimeSuite/blob/master/src/API/lms7_device.cpp#L993-L1093
