### ISSUE TITLE
Could NOT find Python3InterpDbg

### ISSUE THREAD

**Issue by SheetLightning** [pothosware/SoapySDR#346]
I am trying to build SoapySDR and SoapySDRPlay on a Pi with 64-bit Raspberry Pi Os. I get the following when running a cmake:

```
CMake Warning (dev) at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args`
  (Python3InterpDbg) does not match the name of the calling package
  (Python3Interp).  This can lead to problems in calling code that expects
  `find_package` result variables (e.g., `_FOUND`) to follow a certain
  pattern.
Call Stack (most recent call first):
  swig/python3/FindPython3Interp.cmake:62 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  swig/python3/CMakeLists.txt:16 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find Python3InterpDbg (missing: PYTHON3_DBG_EXECUTABLE) 
-- PYTHON3INTERP_FOUND: TRUE
-- PYTHON3_EXECUTABLE: /usr/bin/python3
-- PYTHON3_INSTALL_DIR: ${prefix}/lib/python3.9/dist-packages
-- PYTHON3LIBS_FOUND: TRUE
-- PYTHON3_INCLUDE_DIRS: /usr/include/python3.9;/usr/include/python3.9
-- PYTHON3_LIBRARIES: -L/usr/lib/python3.9/config-3.9-aarch64-linux-gnu -L/usr/lib  -lcrypt -lpthread -ldl  -lutil -lm -lm
```
What is 'Python3InterpDbg' and which library do I need?
When I run make it seems to compile and when I make install afterwards it seems to install, however, when I subsequently try to compile SoapySDRPlay it complains that libsoapysdr is missing. I am running ldconfig after the install.

python --version returns 3.9.2

**Comment by fventuri** [comment]
@SheetLightning - according to this line in `FindPython3Interp.cmake` (https://github.com/pothosware/SoapySDR/blob/master/swig/python3/FindPython3Interp.cmake#L50), `PYTHON3_DBG_EXECUTABLE` is looking for a program called `python3-dbg`. I don't have `python3-dbg` here on my system, and therefore I see the same warning you see, but I am able to build, install, and use SoapySDR and SoapySDRPlay without any problem.

When I run the command `sudo make install` here, I see that it installs `libSoapySDR`under `/usr/local/lib64`.

Do you mind running this command to see where `libSoapySDR` is installed there?
```
find /usr/local -name libSoapySDR\*
```

Thanks,
Franco
