### ISSUE TITLE
Add suport for signal hound

### ISSUE THREAD

**Issue by gaur-yogesh** [pothosware/SoapySDR#349]
Please add support for signal hound SDR such as BB60c etc

**Comment by zuckschwerdt** [comment]
Please show links to Signal Hound API documentation and provide an overview how that API will map to (most) of the functions here: https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Device.h

**Comment by ncorgan** [comment]
This has been on the wishlist for a few years, we just don't/didn't have the hardware: https://github.com/pothosware/SoapySDR/issues/185

I remember from looking into it, it's [pretty convoluted](https://signalhound.com/software/signal-hound-software-development-kit-sdk/). A bunch of device-specific APIs with a mish-mash of OS support between them.

**Comment by ncorgan** [comment]
@gaur-yogesh https://github.com/pothosware/SoapySDR/issues/185#issuecomment-1365121377
