### ISSUE TITLE
UE's can't connect to LimeSDR on a bandwhith 1,4Mhz

### ISSUE THREAD

**Issue by zikkuratti** [pothosware/SoapySDR#372]
Faced with the problem that the LimeSDR USB doesn't start registration procedure then n_prb=6 (Band 8) on prb = 50 it's work well but to me is principal 6.  using SrsRan 21.04 because 22.04 last is drop after 5 call's. Could it be some kind a calibration range problem on this software  driver level?

**Comment by zuckschwerdt** [comment]
SoapySDR (this) is the framework, roughly it's module loading, and module lifecycle (discovery...).

You might be looking for the SoapyLMS7 module from the myriadrf LimeSuite project? https://github.com/myriadrf/LimeSuite/tree/master/SoapyLMS7
