### ISSUE TITLE
View log files

### ISSUE THREAD

**Issue by catkira** [pothosware/SoapySDR#373]
Where can I view logout that is writte like this
`SoapySDR_logf(SoapySDRLogLevel::SOAPY_SDR_FATAL, "test\n");` ?

I am running a programm outside of Pothos, ie SoapySDRUtil. The log output does not appear on stdout.

**Comment by guruofquality** [comment]
Its up to the application that uses the SoapySDR API to register a log handler to control where the logs go. When no handler is registered, the default handler is the stdio

see registerLogHandler in 
* https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Logger.h
* https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Logger.hpp
