### ISSUE TITLE
distutils deprecated

### ISSUE THREAD

**Issue by dl1esk** [pothosware/SoapySDR#375]
-- PYTHON3_EXECUTABLE: /usr/bin/python3
/home/SoapySDR/swig/python3/../python/get_python_lib.py:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.sysconfig import get_python_lib
/home/SoapySDR/swig/python3/../python/get_python_lib.py:4: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  from distutils.sysconfig import get_python_lib

**Comment by VirusFriendly** [comment]
I was able to fix this by editing swig/python/get_python_lib.py as follows

```
import os
import sys
import site
#from distutils.sysconfig import get_python_lib
from sysconfig import get_path

if __name__ == '__main__':
    prefix = sys.argv[1]

    #ask distutils where to install the python module
    #install_dir = get_python_lib(plat_specific=True, prefix=prefix)
    install_dir = get_path('platlib')

    #use sites when the prefix is already recognized
    try:
        paths = [p for p in site.getsitepackages() if p.startswith(prefix)]
        if len(paths) == 1: install_dir = paths[0]
    except AttributeError: pass

    #strip the prefix to return a relative path
    print(os.path.relpath(install_dir, prefix))
```
