### ISSUE TITLE
In the .NET API an exception is thrown when calling Deactivate

### ISSUE THREAD

**Issue by jcma68** [pothosware/SoapySDR#391]
Hello,

In the .NET API, an exception "Stream is already inactive" is thrown when calling Deactivate on a valid stream.

it seems to me that there is a typo in file the file SoapySDR/swig/csharp/assembly/Stream.cs, line 111
`                if(!_active)
                {
                    ret = _device.DeactivateStreamInternal(...
`
should be 
`                if(_active)
                {
                    ret = _device.DeactivateStreamInternal(...
`

**Comment by ncorgan** [comment]
Closed, thanks!
