### ISSUE TITLE
SoapySDRUtil does not find RTL-SDR v4

### ISSUE THREAD

**Issue by frohro** [pothosware/SoapySDR#427]
I am rather new to SoapySDR and the RTL-SDR v4 both, but I expected SoapySDRUtil --find to find the RTL-SDR v4 after I installed the software as per instructions [here](https://www.rtl-sdr.com/V4/) using Ubuntu Linux, but it did not.  rtl_tcp works fine though.

**Comment by zuckschwerdt** [comment]
You need to install https://github.com/pothosware/SoapyRTLSDR

**Comment by frohro** [comment]
It doesn't seem to do the trick to simply install soapysdr-module-rtlsdr from the Ubuntu repo.  Do you concur that I need to build the SoapyRTLSDR from source?

**Comment by zuckschwerdt** [comment]
SoapySDR and the modules need matching versions. They need to show up in `SoapySDRUtil --info`. Either build Soapy all from source or none of it.
