### ISSUE TITLE
Ubuntu 22: Build python3-soapysdr for UHD 4.6

### ISSUE THREAD

**Issue by junkyardhokie** [pothosware/SoapySDR#438]
Is there a way to install python3-soapysdr without also installing the dependency libuhd4.1.0 on Ubuntu 22 using the package manager? I am using libuhd4.6.0 and lib4.1.0 causes compatibility with USRP devices. If there is not a way to do it with the package manager, is there a way to build from source such that python3-soapysdr uses the system version of libuhd? I am already building SoapySDR, SoapyUHD, and UHD from source.

**Comment by zuckschwerdt** [comment]
For https://packages.ubuntu.com/jammy/python3-soapysdr only https://packages.ubuntu.com/jammy/libsoapysdr0.8 is a hard dependency. The soapysdr0.8-module-all can be unselected with
`apt-get install --no-install-recommends --no-install-suggests python3-soapysdr`

**Comment by junkyardhokie** [comment]
Thanks!
