### ISSUE TITLE
Arch linux packaging for SoapySDR and modules

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapySDR#54]
Looking for volunteers interested in creating/testing packages for arch linux. Looks like we need a handful of PKGBUILD files very similar to (https://github.com/pothosware/homebrew-pothos/). We can have a stand-alone arch package repo as well; whatever is best.

Thoughts, volunteers? Let us know in the comments.

**Comment by tomswartz07** [comment]
I have a rough cut (read: minimally tested) PKGBUILD for Arch here: https://github.com/tomswartz07/CubicSDR-PKGBUILDS/blob/master/soapysdr/PKGBUILD

I'd be more than happy to help with the 'official' PKGBUILD file.

**Comment by guruofquality** [comment]
Is there any official naming convention here with the repos: Should I just make PKGBUILDS.git?

**Comment by tomswartz07** [comment]
Well, there are two options:
If you want to keep your PKGBUILDs separate on GitHub, you can name them whatever you want.

When the package is actually submitted to the AUR, you'll need to add their repository as a remote.
It's all documented here: https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages

**Comment by guruofquality** [comment]
Well, I'm making myself an arch vm, and you now should have free reign over the new repo: https://github.com/pothosware/PothosSDR-PKGBUILDS

**Comment by FFY00** [comment]
I think this can be closed as I moved pretty much every SoapySDR module to the official repos.

**Comment by guruofquality** [comment]
cool!
