### ISSUE TITLE
/usr/local/include/SoapySDR/Device.h:60:1: error: unknown type name ‘SoapySDRDevice’ (Using C api)

### ISSUE THREAD

**Issue by jazzkutya** [pothosware/SoapySDR#63]
Hi, i want to learn using SoapySDR with C, but I'm completely blocked by this error.
The source I'm trying to compile with SoapySDR is here: https://github.com/jazzkutya/learnsoapysdr

**Comment by jazzkutya** [comment]
Okay I've noticed that if I compile my stuff with g++ it compiles well. Also I read on http://stackoverflow.com/questions/8096887/mixing-c-and-c-with-cmake that the c source file having main() should be compiled with a c++ compiler. Now let's assume one is having the SoapySDR related code in a separate object and C file and uses a C compiler for that as it has no main(). In this case the problem can be fixed with changing in include/SoapySDR/Device.h:

struct SoapySDRDevice;
struct SoapySDRStream;

change these to lines to:
typedef struct SoapySDRDevice SoapySDRDevice;
typedef struct SoapySDRStream SoapySDRStream;

Should this change be committed to SoapySDR?

**Comment by guruofquality** [comment]
This commit on the cfixes branch should do the trick: https://github.com/pothosware/SoapySDR/commit/7f8d0c93df28bf8039bcb85b5f08630d0335a2c6

thanks for reporting

**Comment by guruofquality** [comment]
Also, your suggested fix is actually nicer, I made the change. :-)

**Comment by jazzkutya** [comment]
thanks, it's working :)

**Comment by jazzkutya** [comment]
just a small note, i wrote the wrong url here for info on mixing C and C++ code, the correct is https://isocpp.org/wiki/faq/mixing-c-and-cpp

**Comment by guruofquality** [comment]
thanks, cfixes branch merged, closing
