### ISSUE TITLE
C client API example

### ISSUE THREAD

**Issue by frspin** [pothosware/SoapySDR#78]
Currently there is example for C++ API (SoapySDRUtil) and for Python API.

Can we have an example of C API usage?

Regards
Franco Spinelli

**Comment by guruofquality** [comment]
Check it out: https://github.com/pothosware/SoapySDR/wiki/C_API_Example

**Comment by frspin** [comment]
Very nice example, tested with latest Github SoapySDR under Ubuntu 14.04 and also 16.04

Thanks a lot

Franco Spinelli

**Comment by guruofquality** [comment]
Glad to hear it. Closing!
