### ISSUE TITLE
compilation error - Could NOT find Python3InterpDbg

### ISSUE THREAD

**Issue by lucasduffey** [pothosware/SoapySDR#90]
Could NOT find Python3InterpDbg (missing:  PYTHON3_DBG_EXECUTABLE)

**Comment by lucasduffey** [comment]
https://github.com/pothosware/SoapySDR/blob/master/python3/FindPython3Interp.cmake#L62

**Comment by guruofquality** [comment]
Its usually not a problem to be missing optional dependencies. The build is looking for python3 development files to build bindings for python3. If you post the output from cmake and the OS that may be helpful.

**Comment by lucasduffey** [comment]
it was failing and I incorrectly assumed this was the problem

I will make a new issue for the real problem
