### ISSUE TITLE
ambiguous naming scheme and documentation

### ISSUE THREAD

**Issue by lucasduffey** [pothosware/SoapySDR#91]
SoapySDR::Device::enumerate returns "SoapySDR::KwargsList", but when I was trying to figure out the datatype of the individual items in KwargsList I noticed a couple issues.

1. "SoapySDR::Device::enumerate" is in "lib/Factory.cpp" instead of "lib/Device.cpp".
2. docs @ http://pothosware.github.io/SoapySDR/doxygen/0.5.1/classSoapySDR_1_1Device.html for "KwargsList SoapySDR::Device::enumerate" do not indicate what datatypes the individual devices are.

Reading the source for "SoapySDR::Device::enumerate", I'm still a little unsure.

**Comment by lucasduffey** [comment]
when I figure this out more, I might try to contribute something useful

**Comment by guruofquality** [comment]
> "SoapySDR::Device::enumerate" is in "lib/Factory.cpp" instead of "lib/Device.cpp".

I guess its a little inconsistent with the naming, but its not really a problem. Its just that the factory calls for discovery and instantiation all share data structures so they go in the same file.

> docs @ http://pothosware.github.io/SoapySDR/doxygen/0.5.1/classSoapySDR_1_1Device.html for "KwargsList SoapySDR::Device::enumerate" do not indicate what datatypes the individual devices are.

It returns a list of key/value maps, where each element of the list can be passed to Device::make() to instantiate a device handle.
