### ISSUE TITLE
Version 0.5.2 does not compile on Raspbian Jessie

### ISSUE THREAD

**Issue by ISSchuster** [pothosware/SoapySDR#98]
I can't compile version 0.5.2 on Raspbian Jessie - 0.5.1 is working fine...

root@raspberrypi:~/SoapySDR/build# make -j4
Scanning dependencies of target docs
Scanning dependencies of target SoapySDR
[  3%] [  7%] [ 11%] [ 14%] Generating documentation with doxygen
Building CXX object lib/CMakeFiles/SoapySDR.dir/Device.cpp.o
Building CXX object lib/CMakeFiles/SoapySDR.dir/Factory.cpp.o
Building CXX object lib/CMakeFiles/SoapySDR.dir/Registry.cpp.o
Warning: ignoring unsupported tag `GROUP_NESTED_COMPOUNDS =' at line 351, file /root/SoapySDR/build/docs/Doxyfile
Warning: ignoring unsupported tag `HIDE_COMPOUND_REFERENCE=' at line 522, file /root/SoapySDR/build/docs/Doxyfile
Warning: ignoring unsupported tag `WARN_AS_ERROR          =' at line 746, file /root/SoapySDR/build/docs/Doxyfile
Warning: ignoring unsupported tag `LATEX_EXTRA_STYLESHEET =' at line 1700, file /root/SoapySDR/build/docs/Doxyfile
Warning: ignoring unsupported tag `LATEX_TIMESTAMP        =' at line 1767, file /root/SoapySDR/build/docs/Doxyfile
Warning: ignoring unsupported tag `RTF_SOURCE_CODE        =' at line 1833, file /root/SoapySDR/build/docs/Doxyfile
Warning: ignoring unsupported tag `PLANTUML_INCLUDE_PATH  =' at line 2367, file /root/SoapySDR/build/docs/Doxyfile
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching for files to process...
Searching for files in directory /root/SoapySDR/include/SoapySDR
Reading and parsing tag files
Parsing files
Preprocessing /root/SoapySDR/include/SoapySDR/Config.h...
Parsing file /root/SoapySDR/include/SoapySDR/Config.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Config.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Config.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Constants.h...
Parsing file /root/SoapySDR/include/SoapySDR/Constants.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Device.h...
Parsing file /root/SoapySDR/include/SoapySDR/Device.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Device.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Device.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Errors.h...
Parsing file /root/SoapySDR/include/SoapySDR/Errors.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Errors.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Errors.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Formats.h...
Parsing file /root/SoapySDR/include/SoapySDR/Formats.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Formats.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Formats.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Logger.h...
Parsing file /root/SoapySDR/include/SoapySDR/Logger.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Logger.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Logger.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Modules.h...
Parsing file /root/SoapySDR/include/SoapySDR/Modules.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Modules.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Modules.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Registry.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Registry.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Time.h...
Parsing file /root/SoapySDR/include/SoapySDR/Time.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Time.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Time.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Types.h...
Parsing file /root/SoapySDR/include/SoapySDR/Types.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Types.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Types.hpp...
Preprocessing /root/SoapySDR/include/SoapySDR/Version.h...
Parsing file /root/SoapySDR/include/SoapySDR/Version.h...
Preprocessing /root/SoapySDR/include/SoapySDR/Version.hpp...
Parsing file /root/SoapySDR/include/SoapySDR/Version.hpp...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Creating members for template instances...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating code for file Config.h...
Generating code for file Config.hpp...
Generating code for file Constants.h...
Generating code for file Device.h...
Generating code for file Device.hpp...
Generating code for file Errors.h...
Generating code for file Errors.hpp...
Generating code for file Formats.h...
Generating code for file Formats.hpp...
Generating code for file Logger.h...
Generating code for file Logger.hpp...
Generating code for file Modules.h...
Generating code for file Modules.hpp...
Generating code for file Registry.hpp...
Generating code for file Time.h...
Generating code for file Time.hpp...
Generating code for file Types.h...
Generating code for file Types.hpp...
Generating code for file Version.h...
Generating code for file Version.hpp...
Generating file documentation...
Generating docs for file Config.h...
Generating docs for file Config.hpp...
Generating docs for file Constants.h...
Generating docs for file Device.h...
Generating docs for file Device.hpp...
Generating docs for file Errors.h...
Generating docs for file Errors.hpp...
Generating docs for file Formats.h...
Generating docs for file Formats.hpp...
Generating docs for file Logger.h...
Generating docs for file Logger.hpp...
Generating docs for file Modules.h...
Generating docs for file Modules.hpp...
Generating docs for file Registry.hpp...
Generating docs for file Time.h...
Generating docs for file Time.hpp...
Generating docs for file Types.h...
Generating docs for file Types.hpp...
Generating docs for file Version.h...
Generating docs for file Version.hpp...
Generating page documentation...
Generating docs for page deprecated...
Generating group documentation...
Generating class documentation...
Generating docs for compound SoapySDRArgInfo...
Generating docs for compound SoapySDRKwargs...
Generating docs for compound SoapySDRRange...
Generating namespace index...
Generating docs for namespace SoapySDR
Generating docs for compound SoapySDR::ArgInfo...
Generating docs for compound SoapySDR::Device...
Generating docs for compound SoapySDR::Range...
Generating docs for compound SoapySDR::Registry...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
Generating SQLITE3 output...
Initializing DB schema...
Generating Sqlite3 output for class SoapySDR::ArgInfo
Generating Sqlite3 output for class SoapySDR::ArgInfo
Generating Sqlite3 output for class SoapySDR::Device
Generating Sqlite3 output for class SoapySDR::Device
Generating Sqlite3 output for class SoapySDR::Range
Generating Sqlite3 output for class SoapySDR::Range
Generating Sqlite3 output for class SoapySDR::Registry
Generating Sqlite3 output for class SoapySDR::Registry
Generating Sqlite3 output for class SoapySDRArgInfo
Generating Sqlite3 output for class SoapySDRArgInfo
Generating Sqlite3 output for class SoapySDRKwargs
Generating Sqlite3 output for class SoapySDRKwargs
Generating Sqlite3 output for class SoapySDRRange
Generating Sqlite3 output for class SoapySDRRange
Generating Sqlite3 output for namespace SoapySDR
Generating Sqlite3 output for file Config.h
Generating Sqlite3 output for file Config.hpp
Generating Sqlite3 output for file Constants.h
Generating Sqlite3 output for file Device.h
Generating Sqlite3 output for file Device.hpp
Generating Sqlite3 output for file Errors.h
Generating Sqlite3 output for file Errors.hpp
Generating Sqlite3 output for file Formats.h
Generating Sqlite3 output for file Formats.hpp
Generating Sqlite3 output for file Logger.h
Generating Sqlite3 output for file Logger.hpp
Generating Sqlite3 output for file Modules.h
Generating Sqlite3 output for file Modules.hpp
Generating Sqlite3 output for file Registry.hpp
Generating Sqlite3 output for file Time.h
Generating Sqlite3 output for file Time.hpp
Generating Sqlite3 output for file Types.h
Generating Sqlite3 output for file Types.hpp
Generating Sqlite3 output for file Version.h
Generating Sqlite3 output for file Version.hpp
Generating Sqlite3 output for page deprecated
lookup cache used 551/65536 hits=3345 misses=556
finished...
[ 14%] Built target docs
[ 18%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Types.cpp.o
[ 22%] Building CXX object lib/CMakeFiles/SoapySDR.dir/NullDevice.cpp.o
[ 25%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Logger.cpp.o
[ 29%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Errors.cpp.o
[ 33%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Formats.cpp.o
[ 37%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Modules.cpp.o
[ 40%] Building CXX object lib/CMakeFiles/SoapySDR.dir/Version.cpp.o
[ 44%] Building CXX object lib/CMakeFiles/SoapySDR.dir/TypesC.cpp.o
[ 48%] Building CXX object lib/CMakeFiles/SoapySDR.dir/ModulesC.cpp.o
[ 51%] Building CXX object lib/CMakeFiles/SoapySDR.dir/VersionC.cpp.o
[ 55%] Building CXX object lib/CMakeFiles/SoapySDR.dir/DeviceC.cpp.o
[ 59%] Building CXX object lib/CMakeFiles/SoapySDR.dir/FactoryC.cpp.o
[ 62%] Building CXX object lib/CMakeFiles/SoapySDR.dir/LoggerC.cpp.o
[ 66%] Building CXX object lib/CMakeFiles/SoapySDR.dir/TimeC.cpp.o
[ 70%] Building CXX object lib/CMakeFiles/SoapySDR.dir/ErrorsC.cpp.o
[ 74%] Building CXX object lib/CMakeFiles/SoapySDR.dir/FormatsC.cpp.o
Linking CXX shared library libSoapySDR.so
[ 74%] Built target SoapySDR
Scanning dependencies of target SoapySDRUtil
Scanning dependencies of target TestKwargsMarkup
Scanning dependencies of target TestTimeConversion
Scanning dependencies of target TestFormatParser
[ 77%] [ 81%] [ 85%] [ 88%] Building CXX object tests/CMakeFiles/TestKwargsMarkup.dir/TestKwargsMarkup.cpp.o
Building CXX object tests/CMakeFiles/TestTimeConversion.dir/TestTimeConversion.cpp.o
Building CXX object tests/CMakeFiles/TestFormatParser.dir/TestFormatParser.cpp.o
Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapySDRUtil.cpp.o
Linking CXX executable TestTimeConversion
[ 88%] Built target TestTimeConversion
[ 92%] Building CXX object apps/CMakeFiles/SoapySDRUtil.dir/SoapySDRProbe.cpp.o
Linking CXX executable TestFormatParser
[ 92%] Built target TestFormatParser
[ 96%] Swig source
Linking CXX executable TestKwargsMarkup
[ 96%] Built target TestKwargsMarkup
Scanning dependencies of target _SoapySDR
[100%] Building CXX object python/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o
Linking CXX executable SoapySDRUtil
[100%] Built target SoapySDRUtil
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5901:22: error: redefinition of âstruct swig::traits<unsigned int>â
   template <> struct traits<unsigned int > {
                      ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5642:22: error: previous definition of âstruct swig::traits<unsigned int>â
   template <> struct traits<size_t > {
                      ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5905:23: error: redefinition of âstruct swig::traits_asval<unsigned int>â
   template <>  struct traits_asval<unsigned int > {
                       ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5646:23: error: previous definition of âstruct swig::traits_asval<unsigned int>â
   template <>  struct traits_asval<size_t > {
                       ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5911:23: error: redefinition of âstruct swig::traits_from<unsigned int>â
   template <>  struct traits_from<unsigned int > {
                       ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5652:23: error: previous definition of âstruct swig::traits_from<unsigned int>â
   template <>  struct traits_from<size_t > {
                       ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5921:22: error: redefinition of âstruct swig::traits<std::vector<unsigned int> >â
  template <>  struct traits<std::vector<unsigned int, std::allocator< unsigned int > > > {
                      ^
/root/SoapySDR/build/python/SoapySDRPYTHON_wrap.cxx:5662:22: error: previous definition of âstruct swig::traits<std::vector<unsigned int> >â
  template <>  struct traits<std::vector<size_t, std::allocator< size_t > > > {
                      ^
python/CMakeFiles/_SoapySDR.dir/build.make:62: recipe for target 'python/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o' failed
make[2]: *** [python/CMakeFiles/_SoapySDR.dir/SoapySDRPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:380: recipe for target 'python/CMakeFiles/_SoapySDR.dir/all' failed
make[1]: *** [python/CMakeFiles/_SoapySDR.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guruofquality** [comment]
@ISSchuster Can you confirm what the branch is because there are no swig or API changes to cause this between 0.5.1 and 0.5.2... However, if you were building **master**, we just added a swig ``%template`` for some new API calls that use``std::vector<unsigned>``, and I think that on some 32-bit platforms size_t is a typedef of unsigned int -- which might cause this issue. Which means that there is a fix to master, but I dont think its for the release tag.

**Comment by ISSchuster** [comment]
OK - my fault... It's the Master... I used "git clone https://github.com/pothosware/SoapySDR.git"

**Comment by guruofquality** [comment]
FYI - This should fix it in the master branch: https://github.com/pothosware/SoapySDR/commit/91aa441fe8aba20027da2da0b2ac2018391190f6
